### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by goshoom** [TrudAX/TRUDUtilsD365#1]
I think there should be a kind of script to install the extension. The target location can be found in Windows registry.

Microsoft used to include a .bat file with code like this:

`for /F "eol=! tokens=2*" %%I IN ('reg query HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0\ExtensionManager\EnabledExtensions /v "DynamicsRainierVSTools-52924ab1-c4fa-47fc-a90d-a5d1e69986bb,1.0"') do set ExtDir=%%J`

Another GitHub project uses a console application as an installer. It has with a single hard-coded path, which clearly works only in certain cases. I made [a pull request with a generic solution](https://github.com/HichemDax/D365FONinjaDevTools/pull/1/commits/043dfb8f8e9d41837bab35222fd5c9babd732052), which could be used for this project too.

**Comment by TrudAX** [comment]
Thanks for the issue Martin. Added install program with your code
