### ISSUE TITLE
AxSecurityEntryPointReferenceForm missing when "Create security privilege" used on Display menu item

### ISSUE THREAD

**Issue by ReneVolkmer** [TrudAX/TRUDUtilsD365#11]
Hello TrudAX,
thank you for creating this tool! I discovered recently that AxSecurityEntryPointReferenceForm part is missing when "Create security privilege" addin function is used on Display menu item. On screenshot bellow, on left side you can see xml when the same is done via VS:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/17122845/148395515-c185e2d0-2dab-48ac-a0c6-1cfef60cdc1d.png">

Missing AxSecurityEntryPointReferenceForm  means field level security is difficult to do as no form/ds/ds_field security can be added/specified. Or am I missing anything? Thank you

**Comment by TrudAX** [comment]
Hi @ReneVolkmer . 
Thank you very much for  reporting this and such detail description. I have fixed this in https://github.com/TrudAX/TRUDUtilsD365/commit/b64a988c1add5002ef7a31aca4d5870437b8c437 and updated release files
