### ISSUE TITLE
Can't install on last VHD (.32) downloadable from LCS

### ISSUE THREAD

**Issue by mrizzari** [TrudAX/TRUDUtilsD365#17]
Hello,

When I try to install TRUDUtils by executing the Powershell script in admin mode like I always did on previous VHDs, it does not work. I get this error :

```
VS extension folder: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\AddinExtensions
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\AddinExtensions\TRUDUtilsD365.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at InstallToVS.Program.Main(String[] args)
Seems that an issue prevented me from doing my job :(
```

I guess there is a slight version change that prevent the InstallToVS.exe to work properly ?

Regards,
Mirko

**Comment by TrudAX** [comment]
Hm, probably the path is changed for local VM(it is working on the cloud VM). But I don't have a new VM now. Can you try to install it manually(see the description for manual install) and send me a path string, I will update the description.
Or maybe you have an idea how to fix the current version of InstallToVS.exe

**Comment by TrudAX** [comment]
It should be fixed for a new .37 VM. Please note - Installation will work for VS2022 only
