### ISSUE TITLE
QueryRunner in query objects

### ISSUE THREAD

**Issue by juliomutley** [TrudAX/TRUDUtilsD365#19]
the idea would be to have a way to test the query and see the results in a "table browser" without waiting to sync

**Comment by TrudAX** [comment]
Thanks for the idea, but it is unclear how addins can do it. Add-ins is for AOT object creation/modification

**Comment by TrudAX** [comment]
I will close this issue, as it is unclear what to do. If you know your SQL text, you can run it using this tool https://denistrunin.com/xpptools-sqlexecute
