### ISSUE TITLE
Problem with VS2022

### ISSUE THREAD

**Issue by lhorvath75** [TrudAX/TRUDUtilsD365#23]
Hi,

I use OneBox VHD 10.0.37 for D365 FnO development. VS2022 is available here, and I would install the Add-In on this version.
The installation is successful, but when calling the VS2022 Add-In menu, it says the following error
![image](https://github.com/TrudAX/TRUDUtilsD365/assets/94899675/11eac06d-50bf-4d85-abcb-a9101e13923d)
If I delete the DLL, the VS2022 extensions are restored.

Thanks in advance for your help

Regards, 
László

**Comment by TrudAX** [comment]
Thanks for the reporting. TRUDUtilsD365 probably should be recompiled for VS2022. How do you get VS2022? As I understand on the OneBox VHD there should be VS2019 used by default

**Comment by lhorvath75** [comment]
The latest 10.0.37 OneBox VHD already uses VS2022.

**Comment by TrudAX** [comment]
Should be fixed with the latest release(I added references from VS2022). Thank you for reporting this, great help for the community

**Comment by lhorvath75** [comment]
Thanks for the quick help.
I really like using the TrudAx extension.

Denis Trunin ***@***.***> ezt írta (időpont: 2023. nov. 19.,
V, 6:26):

**Comment by juliomutley** [comment]
guys did it worked for you, I'm still having issues with Vs2022

**Comment by TrudAX** [comment]
try to manually copy files from the release to this folder

C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\j30535fu.rdl\AddinExtensions

or on one box you can just open the project, and compile it

**Comment by juliomutley** [comment]
Thanks for the quick reply, it worked manually copying and changing the
dynamic config file.
