### ISSUE TITLE
An error while installing

### ISSUE THREAD

**Issue by sarper123** [TrudAX/TRUDUtilsD365#26]
Hello,

I removed my vs 2019 and install vs 2022 but i get an error while using cmd command.

![image](https://github.com/TrudAX/TRUDUtilsD365/assets/51409303/2e82bc7d-43a0-46b8-aa7e-d59e1d4eb44c)

**Comment by TrudAX** [comment]
Probably somewhere, the system keeps the old path. Can you try just manually copy these files to AddinExtensions inside VS2022 folder?

**Comment by sarper123** [comment]
I couldn't find the folders you mention in your guide and I don't know our VM version. Our it guy re-installed the VM for fix my vs. Thank you for help I will try this extension later. For now I caused too much trouble in my recent project.

**Comment by TrudAX** [comment]
So right now two versions exist, the default is 2022, and the old one(needs to be manually downloaded, 2019)
