### ISSUE TITLE
I cannot install the tool.

### ISSUE THREAD

**Issue by ptuerk** [TrudAX/TRUDUtilsD365#3]
I call the InstallToVS.exe and get the following error message: "Could not find D365FO tools in Windows registry."

I do not have the subfolder DynamicsRainierVSTools.
![2018-11-19_14-58-08](https://user-images.githubusercontent.com/14225290/48711520-cb099b80-ec0b-11e8-84e6-cb1eb5443a91.png)

But I can develop on my local dev machine:
![grafik](https://user-images.githubusercontent.com/14225290/48711734-466b4d00-ec0c-11e8-9318-a2094d98ca4c.png)

**Comment by TrudAX** [comment]
Are you using standard one box VM downloaded from LCS? Which version? 
To workaround the issue try to create an empty developer D365FO  add ins project. When you build it it will show you the path in the output window

**Comment by TrudAX** [comment]
The last directory looks correct. My original installation files were created on 8.0, I will try on 8.1 tomorrow. 
You can also try to recompile the project(all references should be taken from the directory on last picture, but 1 level up). I will also try to compile it on 8.1 and let you know

**Comment by ptuerk** [comment]
I have added the missing refrences to your project and this workaround works for me.
Thanks for the quick support

**Comment by TrudAX** [comment]
Just tested on 8.1 local VM, and standard installation was fine. Probably you need to run install program as Administrator 
![image](https://user-images.githubusercontent.com/26786918/48814659-50658b00-ed87-11e8-87c7-b3ceb7ae3cd1.png)

**Comment by ptuerk** [comment]
I run the install program as Administrator

![grafik](https://user-images.githubusercontent.com/14225290/48848522-633a8880-eda4-11e8-971e-ddf43b1a1d76.png)

**Comment by TrudAX** [comment]
This has been fixed(thanks for @goshoom), will be available in the new release. Thanks for the reporting
