### ISSUE TITLE
Expand table builder by creating a privilege

### ISSUE THREAD

**Issue by ptuerk** [TrudAX/TRUDUtilsD365#6]
Can you please expand the table builder by creating a privilege?
![grafik](https://user-images.githubusercontent.com/14225290/53743472-2ef26000-3e9b-11e9-8f8e-151a84fb9d5c.png)

**Comment by TrudAX** [comment]
There is a separate tool for this - Create security privilege. 
If you want, you can add it's parameters to Table builder dialog. But please use SecurityPrivilegeBuilderParms class to create a Privilege.

**Comment by TrudAX** [comment]
Added in https://github.com/TrudAX/TRUDUtilsD365/releases/tag/2.1.0
