### ISSUE TITLE
Missing field group label in fields builder

### ISSUE THREAD

**Issue by ptuerk** [TrudAX/TRUDUtilsD365#8]
It is not possible to assign a label to the field group.

Can you please add this field?

Thanks in advance

![2019-05-14_14-07-43](https://user-images.githubusercontent.com/14225290/57700191-b86f9c80-7659-11e9-9c23-3258b2ccc15f.png)

**Comment by TrudAX** [comment]
Added in 2.1.1. Thanks for the idea
